# Generated by Django 5.0.6 on 2024-07-05 10:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databaseAPI', '0002_alter_joblevelmodel_job_level_registration_date_and_more'),
        ('userloginAPI', '0005_alter_recruiteremailverification_expire_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescriptionModel',
            fields=[
                ('job_position_name', models.CharField(default=None, max_length=100)),
                ('job_level_name', models.CharField(default=None, max_length=100)),
                ('job_tilte', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('job_description_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('salary_min', models.CharField(default=None, max_length=100)),
                ('salary_max', models.CharField(default=None, max_length=100)),
                ('number_of_vacancy', models.CharField(default=None, max_length=200)),
                ('job_description_action', models.CharField(blank=True, default='active', max_length=60, null=True)),
                ('job_description_registration_date', models.DateTimeField(default=datetime.datetime(2024, 7, 5, 16, 25, 56, 522999))),
                ('job_level', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='databaseAPI.joblevelmodel')),
                ('job_position', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='databaseAPI.jobpositionmodel')),
                ('recruiter_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userloginAPI.recruitermodel')),
            ],
            options={
                'db_table': 'recruiter_job_desc_tb',
            },
        ),
        migrations.CreateModel(
            name='JobDescriptionUploadModel',
            fields=[
                ('job_description_upload_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('job_description_upload_file', models.FileField(blank=True, default=None, null=True, upload_to='job_descriptions/')),
                ('job_description_upload_registration_date', models.DateTimeField(default=datetime.datetime(2024, 7, 5, 16, 25, 56, 523996))),
                ('job_description', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recruiterAPI.jobdescriptionmodel')),
                ('recruiter_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userloginAPI.recruitermodel')),
            ],
            options={
                'db_table': 'recruiter_job_desc_upload_tb',
            },
        ),
    ]
