# Generated by Django 5.0.6 on 2024-07-06 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescriptionmodel',
            name='number_of_vacancy',
        ),
        migrations.RemoveField(
            model_name='jobdescriptionmodel',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='jobdescriptionmodel',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='jobdescriptionmodel',
            name='job_description_upload_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='job_descriptions/'),
        ),
        migrations.AlterField(
            model_name='jobdescriptionmodel',
            name='job_description_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 12, 10, 38, 124539)),
        ),
        migrations.DeleteModel(
            name='JobDescriptionUploadModel',
        ),
    ]
