# Generated by Django 5.0.6 on 2024-07-06 17:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterAPI', '0002_remove_jobdescriptionmodel_number_of_vacancy_and_more'),
        ('userloginAPI', '0007_rename_user_created_at_recruiteremailverification_user_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescriptionmodel',
            name='job_description_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 22, 37, 23, 935881)),
        ),
        migrations.CreateModel(
            name='RecruiterBulkResumeUploadModel',
            fields=[
                ('recruiter_bulk_resume_upload_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('recruiter_bulk_resume_upload', models.FileField(blank=True, default=None, upload_to='recruiter_resumesUpload/')),
                ('recruiter_bulk_resume_upload_registration_date', models.DateTimeField(default=datetime.datetime(2024, 7, 6, 22, 37, 23, 935881))),
                ('recruiter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userloginAPI.recruitermodel')),
            ],
            options={
                'db_table': 'recruiter_bulk_resume_upload_tb',
            },
        ),
        migrations.CreateModel(
            name='RecruiterResumeCandidateModel',
            fields=[
                ('recruiter_resume_candidate_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('recruiter_resume_candidate_file_path', models.TextField(blank=True, default=None, null=True)),
                ('recruiter_resume_candidate_extracted_text', models.TextField(blank=True, default=None, null=True)),
                ('recruiter_resume_candidate_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('recruiter_resume_candidate_gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('recruiter_resume_candidate_experience', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('recruiter_resume_candidate_nationality', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('recruiter_resume_candidate_url', models.TextField(blank=True, default=None, null=True)),
                ('recruiter_resume_candidate_bookmark', models.BooleanField(default=False)),
                ('recruiter_resume_candidate_firstpage_image', models.FileField(blank=True, default=None, upload_to='resume_firstpage_images/')),
                ('recruiter_resume_candidate_ai_compare_score', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('recruiter_resume_candidate_registration_date', models.DateTimeField(default=datetime.datetime(2024, 7, 6, 22, 37, 23, 935881))),
                ('job_description', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recruiterAPI.jobdescriptionmodel')),
                ('recruiter_bulk_resume_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recruiterAPI.recruiterbulkresumeuploadmodel')),
                ('recruiter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userloginAPI.recruitermodel')),
            ],
            options={
                'db_table': 'recruiter_resume_candidate_tb',
            },
        ),
    ]
