# Generated by Django 5.0.7 on 2024-07-17 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterAPI', '0003_alter_jobdescriptionmodel_job_description_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescriptionmodel',
            name='job_description_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 15, 35, 47, 778419)),
        ),
        migrations.AlterField(
            model_name='recruiterbulkresumeuploadmodel',
            name='recruiter_bulk_resume_upload_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 15, 35, 47, 779413)),
        ),
        migrations.AlterField(
            model_name='recruiterresumecandidatemodel',
            name='recruiter_resume_candidate_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 15, 35, 47, 780411)),
        ),
    ]
