# Generated by Django 5.0.6 on 2024-07-04 11:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterModel',
            fields=[
                ('recruiter_user_id', models.CharField(default='None', max_length=60, primary_key=True, serialize=False)),
                ('recruiter_user_firstname', models.CharField(blank=True, default='None', max_length=30, null=True)),
                ('recruiter_user_lastname', models.CharField(blank=True, default='None', max_length=30, null=True)),
                ('recruiter_user_mobileno', models.CharField(blank=True, default='None', max_length=15, null=True)),
                ('recruiter_user_email', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('recruiter_user_password', models.CharField(blank=True, default='None', max_length=30, null=True)),
                ('recruiter_user_is_action', models.BooleanField(default=True)),
                ('recruiter_user_is_verified', models.BooleanField(default=False)),
                ('recruiter_user_is_loggedin', models.BooleanField(default=False)),
                ('recruiter_user_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recruiter_user_tb',
            },
        ),
        migrations.CreateModel(
            name='RecruiterEmailVerification',
            fields=[
                ('recruiter_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userloginAPI.recruitermodel')),
                ('OTP_verify', models.CharField(max_length=10)),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2024, 7, 4, 16, 40, 8, 124208))),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recruiter_email_verification',
            },
        ),
    ]
