# Generated by Django 5.0.6 on 2024-07-04 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userloginAPI', '0002_alter_recruiteremailverification_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiteremailverification',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 17, 33, 36, 495348)),
        ),
        migrations.AlterField(
            model_name='recruitermodel',
            name='recruiter_user_password',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
