# Generated by Django 5.0.6 on 2024-07-05 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userloginAPI', '0003_alter_recruiteremailverification_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiteremailverification',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 12, 58, 47, 116036)),
        ),
    ]
