# Generated by Django 5.0.6 on 2024-07-06 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userloginAPI', '0005_alter_recruiteremailverification_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiteremailverification',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 12, 10, 38, 119543)),
        ),
    ]
