# Generated by Django 5.0.6 on 2024-07-06 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userloginAPI', '0006_alter_recruiteremailverification_expire_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiteremailverification',
            old_name='user_created_at',
            new_name='user_registration_date',
        ),
        migrations.RenameField(
            model_name='recruitermodel',
            old_name='recruiter_user_created_at',
            new_name='recruiter_user_registration_date',
        ),
        migrations.AlterField(
            model_name='recruiteremailverification',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 22, 37, 23, 930883)),
        ),
    ]
