# Generated by Django 5.0.7 on 2024-07-17 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userloginAPI', '0007_rename_user_created_at_recruiteremailverification_user_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiteremailverification',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 15, 35, 47, 773411)),
        ),
    ]
